# Generated by Django 2.1.4 on 2019-02-26 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='影名')),
                ('long', models.CharField(max_length=60, null=True, verbose_name='片长')),
                ('rank', models.FloatField(verbose_name='评分')),
                ('star_num', models.CharField(max_length=15, null=True, verbose_name='评价人数')),
                ('year', models.CharField(max_length=100, null=True, verbose_name='上映日期')),
                ('_class', models.CharField(max_length=50, null=True, verbose_name='类型')),
                ('countries', models.CharField(max_length=50, null=True, verbose_name='制片国家/地区')),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('review', models.TextField(null=True, verbose_name='简评')),
                ('details', models.TextField(null=True, verbose_name='详细信息')),
                ('poster', models.CharField(default=None, max_length=60, null=True, verbose_name='电影海报')),
                ('image', models.TextField(default=None, null=True, verbose_name='电影剧照')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
            },
        ),
        migrations.CreateModel(
            name='MPR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(choices=[('1', '导演'), ('2', '编剧'), ('3', '演员')], max_length=10, verbose_name='职位')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.Movie', verbose_name='电影')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='person.Person', verbose_name='人物')),
            ],
            options={
                'verbose_name': '电影演员关系',
                'verbose_name_plural': '电影演员关系',
            },
        ),
    ]
