# Generated by Django 2.1.4 on 2019-02-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpr',
            old_name='_type',
            new_name='type',
        ),
    ]
