# Generated by Django 2.1.4 on 2019-03-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
