# Generated by Django 2.1.4 on 2019-03-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20190306_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='用户头像'),
        ),
    ]
