# Generated by Django 2.1.4 on 2019-03-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20190306_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('movie_id', models.CharField(blank=True, default=None, max_length=50)),
                ('person_id', models.CharField(blank=True, default=None, max_length=50)),
                ('type', models.CharField(choices=[(1, '电影'), (2, '人物')], max_length=3)),
            ],
        ),
    ]
