# Generated by Django 2.1.4 on 2019-03-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='movie_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='person_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
