# Generated by Django 2.1.4 on 2019-03-06 20:17

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('poster', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户头像')),
                ('motto', models.CharField(blank=True, max_length=200, null=True, verbose_name='座右铭')),
                ('introduce', models.TextField(blank=True, null=True, verbose_name='个人简介')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='registing_user',
            name='poster',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
