# Generated by Django 2.1.7 on 2019-03-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registing_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Email_code', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Resetting_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('Email_code', models.CharField(max_length=128)),
            ],
        ),
    ]
