# Generated by Django 2.1.4 on 2019-03-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('xadmin', '0001_initial'),
        ('movie', '0001_initial'),
        ('user', '0002_auto_20190306_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
